### PR TITLE
Add hunter support

### PR DESCRIPTION
**Pull request by caseymcc**
This is a partial, I will add more if there is interest in it.

Curious if you all would like hunter support in the project? hunter is a cmake based package manager that will download and compile required dependencies, more information can be found here https://github.com/ruslo/hunter and a list of available packages here https://docs.hunter.sh/en/latest/packages.html.

I have added it under a cmake flag GWK_USE_HUNTER which is defaulted to OFF and only for RENDER_OPENGL_CORE, if you would like to test it just pull this commit and run cmake with `-DGWK_USE_HUNTER=ON -DRENDER_OPENGL_CORE=ON` and it will fetch and compile glm, glew and glfw and link them automatically. It only downloads and compiles them once unless the build configuration changes or you update to a newer version of hunter.

If there is interest I will make changes for the remaining packages available in hunter.

### CODE REVIEW

**Comment by billyquith** [comment]
Out of interest, how widely used is it? I've not heard of it before.

**Comment by caseymcc** [comment]
Couldn't say for sure, I can just go by experience working with it and for the most part it just works. The community seems to be pretty good, you can see on the github page that it has about 113 contributors (mostly people adding packages, myself included) and growing. Ruslo which is the caretaker responds amazingly fast and there is generally a knowledgeable group around to get things done. If you have never used it, it will generally make you development easier.

Adding packages is relatively straight forward and best of all it is just cmake, nothing else required. Even packages that are not cmake based someone has gone through the effort to support it. Generally on a project that uses "modern" cmake adding it as a package to hunter is only a few lines.

At some point I will package GWork for hunter, if I can get any changes needed into the main repo then should be straight forward. The changes are generally just the addtion of HunterGate.cmake and the hunter calls, everything is standard cmake so even if hunter is not used the cmake setup should be the same. If not the changes will just go into a hunter packages repo (https://github.com/hunter-packages), just makes version updating a little more tedious.

**Comment by caseymcc** [comment]
Fixed it up for OpenGL, OpenGLCore and SDL2. SDL2 had a compile bug but was a quick fix.

**Comment by billyquith** [comment]
I don't want to complicate the cmake config with conditionals for each package manager. There are other package managers that are more popular than Hunter, like Conan.

I'm not sure how to arrange it, but perhaps each PM could have a Gwork Cmake config that sets up the environment before running the Gwork config. E.g. makes sure the dependencies are fetched and supplies the correct paths.

**Pull request closed without merging**
