### PR TITLE
Add option to support SFML 2.5 on Windows

### PR DESCRIPTION
**Pull request by jhlgns**
Changes involve linking Gwork${GWK_RENDER_NAME} with the GWK_RENDER_LIBRARIES, finding OpenGL as SFML 2.5 depends on it (only on Windows) and setting the CONFIG flag when finding SFML with the option 'USE_SFML_CONFIG' enabled.
Tested on Windows 10 and Debian Buster/Sid.

### CODE REVIEW

**Comment by jhlgns** [comment]
I don't know what went wrong, but obviously only the last commit is what i have done... Sorry, this is my first PR :confused:

**Comment by eXpl0it3r** [comment]
Sounds like you branched it off from the wrong branch or targeted the wrong branch.
Not actually sure what's the idea of the `gwork` or `develop` branch myself 🤔

**Comment by billyquith** [comment]
> I don't know what went wrong

I think you must have branched from an old version, then updated, and then committed your fix.

> Not actually sure what's the idea of the `gwork` or `develop` branch myself

"gwork" is the Gwork master branch, which forked from the GWEN master. "develop" the development branch, info which all work should go before being versioned, documented, tested, etc and push into "gwork".

**Comment by eXpl0it3r** [comment]
Okay, so this PR should branch of develop and target develop?

**Comment by billyquith** [comment]
> Okay, so this PR should branch of develop and target develop?

Ideally. The PR should reflect just the change being made and any remedial work.

**Comment by jhlgns** [comment]
> Okay, so this PR should branch of develop and target develop?

I was 99% sure that this was what I did. I'll retry later :smile:

**Pull request closed without merging**
