### PR TITLE
Fixed ResizableControl::DisableResizing not working properly.

### PR DESCRIPTION
**Pull request by eXpl0it3r**
Applied patch from #41.

### CODE REVIEW

**Comment by ipo** [comment]
Do you want to know what is funny?  After all the back and forth this doesn't even work properly, I had to patch the patch.

Close this and use https://github.com/billyquith/GWork/pull/44 instead.

**Comment by eXpl0it3r** [comment]
...

**Comment by billyquith** [comment]
> I had to patch the patch.

This is one of the reasons that PRs are better. There are continuous integration tests running for Gwork.

If you create a fork on Github you can go to Travis and create your own test, so you can see if your fork works before you create a PR. And the PR is tested.

**Comment by ipo** [comment]
> If you create a fork on Github you can go to Travis and create your own test, so you can see if your fork works before you create a PR. And the PR is tested.

What kind of tests do you mean?  All I see at a cursory glance in Travis is 'does it compile' tests.  There are no unit-tests or similar, the closest I can find is the demo executable.

**Comment by billyquith** [comment]
There are no unit tests as such, just a functional test, called "Unit Test". Sample is compiled with a null target and contains most of the functionality. This was good enough to find your bug.

It would be nice to have automated testing so screenshots could be taken of test screens and compared against a reference to see if a change broken appearance.

**Pull request closed without merging**
